<div class="rt-segment">

    <h3><span style="color: red"><?php 
echo  __( 'IMPORTANT: ', 'better-robots-txt' ) ;
?></span><?php 
echo  __( 'REMOVE THE NOINDEX-NOFOLLOW TAG (GENERATED BY WORDPRESS):', 'better-robots-txt' ) ;
?></h3>
                
    <div class="rt-row">
    
        <div class="rt-column col-3">
            <span class="rt-label"><?php 
echo  __( 'Search engine visibility', 'better-robots-txt' ) ;
?></span>
        </div>
        
        <div class="rt-column col-9">

        
        
            <div class="rt-switch-radio dual-btns">

                <?php 
// free only
?>

                <input type="radio" id="blog_public-btn1" value="" disabled />
                <label for="blog_public-btn1"><?php 
echo  __( 'Allow', 'better-robots-txt' ) ;
?></label>

                <input type="radio" id="blog_public-btn2" value="" checked="checked" />
                <label for="blog_public-btn2"><?php 
echo  __( 'Disable', 'better-robots-txt' ) ;
?></label>

                <?php 
// end free only
?>

                <div class="rt-tooltip">
                    <span class="dashicons dashicons-editor-help"></span>
                    <span class="rt-tooltiptext"><?php 
echo  __( 'This feature will remove/add this tag: &lt;meta name="robots" content="noindex, follow"&gt;', 'better-robots-txt' ) ;
?></span>
                </div>
        
            </div>

            <?php 
// free only
?>
            <div class="rt-alert rt-info">
                <span class="closebtn">&times;</span> 
                <?php 
echo  $get_pro . " " . __( 'Search engine visibility', 'better-robots-txt' ) ;
?>
            </div>
            <?php 
?>

        </div>

    </div>

    <div class="rt-note" style="font-size: 13px; line-height: 150%; margin-bottom: 10px">This feature MUST BE enabled, by default, in order to UNLOCK your website visibility and make your Robots.txt usable. This tag (NoIndex, NoFollow), generated by Wordpress, is sometimes activated (by mistake or voluntary) when your website is under-development. If you see only 2 rules to your robots.txt, if you have no organic traffic and/or if you get notifications from the Google search Console that your website is " blocked" to search engines (despite an optimized robots.txt), we strongly recommend to enable this feature.</div>
    
</div>