<div class="wrap rt-containter">

    <?php include 'inc/top.view.php'; ?>

    <!-- start main settings column -->
    <div class="rt-row">
        <div class="rt-column col-9">
            <div id="rt_app" class="rt-main">
                <form method="post">

                    <?php wp_nonce_field( 'rt__settings', 'rt__nonce' ); ?>
                    
                    <br />

                    <div class="rt-note">
                        <p><?php echo sprintf( wp_kses( __( 'Did you know that when you optimize your Robots.txt, you maximize your site’s crawlability (& your ranking on search engines) but you help reducing your site’s ecological footprint and, at your level, the greenhouse gas (CO2) production generated by major search engines? Read this <a href="%s" target="_blank">article</a> for more info.', 'better-robots-txt' ), array(  'a' => array( 'href' => array(), 'target' => array() ) ) ), esc_url( "https://better-robots.com/how-to-save-the-planet-with-your-website/" ) ); ?></p>
                    </div>
                    <br />
                    <div class="rt-note btn">
                        <p><?php echo sprintf( wp_kses( __( 'Please check your robots.txt before and after optimization (if you don\'t see changes, please read FAQ) &nbsp; <a href="%1s" target="_blank" class="note-btn">Your Robots.txt</a>', 'better-robots-txt' ), array(  'a' => array( 'href' => array(), 'target' => array(), 'class' => array() ) ) ), esc_url( home_url() ."/robots.txt" ) ); ?></p>
                    </div>
                    
                    <?php 
                        include 'steps/seo-visibility.view.php';

                        foreach ( range(1, 12) as $number) {
                            include 'steps/step'.$number.'.view.php';
                        }
                    ?>
                    
                <div class="rt-note btn">
                    <p><?php echo sprintf( wp_kses( __( 'Don’t forget to use our « Robots.txt post META BOX » for manual exclusions (if required). &nbsp;<a href="%s" target="_blank">META BOX feature</a>', "better-robots-txt" ), array(  'a' => array( 'href' => array(), 'target' => array() ) ) ), esc_url( ROBOTS_PLUGIN_DIR . '/admin/assets/imgs/meta-box.jpg' ) ); ?></p>
                </div>


            <div class="rt-segment">

                <div class="rt-row">

                    <div class="rt-column col-4">
                        <span class="rt-label"><?php 
                            echo  esc_html__( 'Delete Settings', "better-robots-txt" ) ;
                        ?></span>
                    </div>

                    <div class="rt-column col-8">
                        <label class="rt-switch">
                            <input type="checkbox" id="remove_settings" name="remove_settings" value="remove_settings"
                            <?php 
                                if ( $options::check('remove_settings') ) { echo  'checked="checked"' ;  }
                            ?> />
                            <span class="rt-slider rt-round"></span>
                        </label>
                        &nbsp;
                        <span><?php 
                            echo  esc_html__( 'Checking this box will remove all settings when you deactivate plugin.', "better-robots-txt" ) ;
                        ?></span>
                    </div>

                </div>

            </div>
                
            <div class="rt-submit"><input type="submit" name="update" class="button-primary" value="<?php echo  esc_html__('Save Changes', "better-robots-txt");?>" /></div>

            </form>

            <div class="rt-note"><p><?php echo __( "Note: Better Robots.txt creates a virtual robots.txt file. Please make sure that your permalinks are enabled and there is no physical robots.txt file on your server. If you're using any kind of cache then make sure to clear it after Saving Changes. Please read FAQ for more details.", "better-robots-txt" ); ?></p></div>
    
            </div>
            <!-- end rt-main -->
        </div>
        <!-- end main settings rt-column col-8 -->

        <div class="rt-column col-3 rt-txt">

            <?php include 'inc/side.view.php'; ?>

        </div>

    </div>

</div>