<?php defined('ABSPATH') or die('No script kiddies please!!');?>
<div class="sc-etab-description">
<h3><?php _e('Shortcode Usage', 'everest-tab'); ?></h3>
<div class="etab_sc_parameters_wrapper clearfix">
    <h5>Shortcode Parameters</h5>
    <p><?php _e('In our plugin there are two type of shortcode available. One tab shortcode is generated using custom post type where you can create multiple tab and add its content with many advanced componenets
        i.e Go to "Everest Tab" > Add New of admin left menu page and create multiple tab adding new page and set specific components
        and then save all data. On successfull saving all data you will find its shortcode on right metabox Shortcode Usage section.', ETAB_TD); ?>

        <br /><?php _e('Whereas, another shortcode, you can generate simply by choosing all required options on your post editor
        page.You can generate shortcode by enabling above checkbox with options to "Enable Shortcode Generator" which on enabling you will find
        "Everest Tab Shortcode" Button on all edit post, page and post type page respectively.', ETAB_TD); ?>

    </p>
    <p><?php _e('Available Custom Shortcode Parameters: ', ETAB_TD); ?></p>
    <ul>
        <li><strong>template</strong> : <?php _e('This parameter help you to change the template set for tab shortcode.Our plugin contains altogether 22 pre defined and beautifully designed tab templates.', ETAB_TD); ?>

            <p>e.g., [etabs slug="slug-here" template="template4"]</p>
        </li>
        <li><strong>orientation</strong> : <?php _e('Our plugin provides orientation type as horizontal and vertical for tab. You can pass tab orientation using shortcode by using orientation="horizontal" or orientation="vertical" and so on as parameter on shortcode.', ETAB_TD); ?>

            <p>e.g., [etabs slug="slug-here" template="template4" orientation="vertical"]</p>
        </li>
        <li><strong>column</strong> : <?php _e('You can even change the column width of tab. Our plugin provides 1-6 column which width percentage is defined as 6 (100% Width),5 (83% Width),4 (66% Width),3 (50% Width),2 (32% Width) and 1 (15% Width) respectively.', ETAB_TD); ?>
            <p>e.g.,[etabs slug="slug-here" template="template4" orientation="vertical" column="5"]</p>
        </li>
    </ul>
    <p><?php _e('Another Advanced Everest Tab Shortcode Parameters & Shortcode Structure:', ETAB_TD); ?></p>
    <p><?php _e('Create your own html structure and automatically changed its structure into tab using shortcode generated from "Everest Tab Shortcode" To get this button work and enable on your edit post, page, you simply have to enable above settings as "Enable Shortcode Generator" first of all. Then you can view on any edit page or post where on top of wp editor section, you will find an extra button which is generated by our plugin named "Everest Tab Shortcode". Click on the button and you will see popup form with various configuration options as follows:', ETAB_TD); ?>
    </p>
    <ul>
        <li><strong>template</strong> : <?php _e('Set template for this tab. Altogether 22 pre defined templates available. Default template 1 will be set. ', ETAB_TD); ?>
         
        </li>
        <li><strong>orientation</strong> : <?php _e('Our plugin provides orientation type as horizontal and vertical for tab.Set tab orientation as horizontal vertical.', ETAB_TD); ?>
        
        </li>
        <li><strong>column</strong> : <?php _e('Even change the column width of tab. Our plugin provides 1-6 column which width percentage is defined as 6 (100% Width),5 (83% Width), 4 (66% Width),3 (50% Width),2 (32% Width) and 1 (15% Width) respectively.', ETAB_TD); ?>
        </li>
        <li><strong>Position</strong> : <?php _e('Set Position of tab title according to orientation based.', ETAB_TD); ?>
         </li>
        <li><strong>Icon Position</strong> : <?php _e('Set Icon Position of tab title. Options available are left , right and top of content.', ETAB_TD); ?>
        </li>
        <li><strong>Trigger Event</strong> : <?php _e('Set Trigger Event as On hover or On Click tab title to display tab content.', ETAB_TD); ?>
        </li>
        <li><strong>Number of Tabs</strong> : <?php _e('Set Total number of tab you want to generate. Below is one of example of tab shortcode with total number of tabs set as 3 with unique id and title which will be generated automatically and similarly, you can modify the title name and content as per your requirement.', ETAB_TD); ?>
        </li>
        <li><strong>Tab Content Animation</strong> : <?php _e('Set tab animation for tab content.', ETAB_TD); ?>
       </li>
    </ul>
    <h5> <?php _e('Below is one of Generated Shortcode example after setting options and inserting into editor:', ETAB_TD); ?>
    </h5>
      <p class="description"> <?php _e('To add shortcode with your own html to generate tab automatically simply follow below steps and Go to ', ETAB_TD); ?>
<a href="<?php echo $admin_url;?>post-new.php" target="_blank"><?php _e('Add New Page',ETAB_TD);?></a><p><?php _e('and Click on button "Everest Tab Shortcode" above wp editor and configure options.', ETAB_TD); ?></p>
    <p><?php _e('Shortcode Clarification: ', ETAB_TD); ?>
    <ul>
        <li><?php _e('Below shortcode specify orientation as vertical with template 6 layout and total width column as 5.', ETAB_TD); ?></li>
        <li> <?php _e('Similarly, we have set vertical orientation tab title position as vertical top right, set icon position as top of the title with trigger event as on click. 
            You can even change it on hover simply by replacing on_hover instead of on_click.', ETAB_TD); ?>
        </li>
        <li><?php _e('Next,', ETAB_TD); ?>
         [everest_tab_title_wrap tab_id='etab-bUYHQayuJQ'] <?php _e('is main wrapper for tab title with unique id auto generated.', ETAB_TD); ?> </li>
        <li>[everest_tab id='tab1bUYHQayuJQ' title='Title1' active='1'][/everest_tab] 
        <?php _e('is shortcode generated for each tab title where on title attribute you can replace required tab title and active = 1 simply specify the active tab is first tab. ', ETAB_TD); ?> 
        <strong> Note: active attribute will only set on one tab title shortcode.</strong></li>
        <li><?php _e('Similarly, for tab content, its main wrapper is generated as [everest_tab_content_wrap]. ', ETAB_TD); ?> 
        </li>
        <li>[everest_tab_content] <?php _e('is main content wrapper with unique trigger id similar to ', ETAB_TD); ?> 
        [everest_tab id='tab1bUYHQayuJQ' title='Title1' active='1'][/everest_tab]<?php _e('so that on click tab title with id "tab1bUYHQayuJQ" its specific tab content will be displayed. ', ETAB_TD); ?> </li>
        <li><?php _e('Then tab content shortcode  will follow as', ETAB_TD); ?> [everest_tab_content trigger='tab1bUYHQayuJQ' tab_id='etab-bUYHQayuJQ' animation='fadeInUp'] Content1 [/everest_tab_content] here on "Content1" you can replace with your content for all tab.</li>
        <li><?php _e('At Last, ', ETAB_TD); ?>[/everest_tab_content_wrap] <?php _e('will close main content wrapper', ETAB_TD); ?></li> 
        <li>[/everest_tabs_wrap] <?php _e('will close whole shortcode wrapper.', ETAB_TD); ?>  </li>
    </ul>
    <p> e.g.,
    <p>[everest_tabs_wrap orientation='vertical' template='template16' column='5' position='vertical-top-right' icon_position='top' trigger_event='on_click']</p>
       <p class="move-sc">[everest_tab_title_wrap tab_id='etab-bUYHQayuJQ']</p>
      <p class="move-sc1">   [everest_tab id='tab1bUYHQayuJQ' title='Title1' active='1'][/everest_tab]</p>
      <p class="move-sc1">    [everest_tab id='tab2bUYHQayuJQ' title='Title2'][/everest_tab]</p>
       <p class="move-sc1">   [everest_tab id='tab3bUYHQayuJQ' title='Title3'][/everest_tab]</p>
      <p class="move-sc">[/everest_tab_title_wrap]</p>

        <p class="move-sc">  [everest_tab_content_wrap]</p>
      <p class="move-sc1">  [everest_tab_content trigger='tab1bUYHQayuJQ' tab_id='etab-bUYHQayuJQ' animation='fadeInUp'] Content1 [/everest_tab_content]</p>
       <p class="move-sc1">  [everest_tab_content trigger='tab2bUYHQayuJQ' tab_id='etab-bUYHQayuJQ' animation='fadeInUp'] Content2 [/everest_tab_content]</p>
      <p class="move-sc1">   [everest_tab_content trigger='tab3bUYHQayuJQ' tab_id='etab-bUYHQayuJQ' animation='fadeInUp'] Content3 [/everest_tab_content]</p>
     <p class="move-sc">  [/everest_tab_content_wrap]</p>
      <p>[/everest_tabs_wrap]</p>
    </p>
</div>
</div>